"""Agrega columna capacidad a restaurantes

Revision ID: 450b59bc4881
Revises: 
Create Date: 2026-09-16 19:18:20.942548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450b59bc4881'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidad', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.drop_column('capacidad')

    # ### end Alembic commands ###
