FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 5000
# Levantamos el servidor de desarrollo en el puerto 5000
CMD ["python", "manage.py", "runserver", "0.0.0.0:5000"]